ALTER TABLE "SiteSetting" ADD COLUMN "aboutGoals" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN "aboutPlaces" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN "aboutExpect" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSetting" ADD COLUMN "aboutRules" TEXT NOT NULL DEFAULT '';
