ALTER TABLE "SiteSetting" ADD COLUMN "textHeadlinePx" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "SiteSetting" ADD COLUMN "textSectionPx" INTEGER NOT NULL DEFAULT 36;
ALTER TABLE "SiteSetting" ADD COLUMN "textIntroPx" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "SiteSetting" ADD COLUMN "textBodyPx" INTEGER NOT NULL DEFAULT 14;
